In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import svm
from sklearn.svm import SVC, LinearSVC

Sebagai percobaan gunakan data dengan pemanggilan data sebagai berikut

In [ ]:
data = pd.read_csv('bill_authentication.csv')
data.head()

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

pecah data menjadi data atribut dan data kelas

In [ ]:
X = data.drop('Class', axis=1)
Y = data['Class']

gunakan splitting untuk membagi data tersebut dalam data training dan data testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20)

Gunakan metode fit pada SVC untuk membentuk model SVM dari data training

In [ ]:
modelSVM = svm.SVC(kernel='linear')
modelSVM.fit(X_train, Y_train)

SVC(kernel='linear')

gunakan model SVM dari hasill data training untuk membuat prediksi dari data

In [ ]:
Y_pred = modelSVM.predict(X_test)
Y_pred

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1])

Jalankan confusion matrix, precision, recall dan F1 untuk mengevaluasi hasil klasifikasi.

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print('akurasi : ', accuracy_score(Y_test, Y_pred))

[[147   2]
 [  1 125]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       149
           1       0.98      0.99      0.99       126

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

akurasi :  0.9890909090909091

Implementasi kernel pada SVM

In [ ]:
b = pd.read_csv('iris-data-prak.csv')
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
irisdata = pd.read_csv('iris-data-prak.csv', names=colnames, delimiter=';', skiprows=2)
irisdata.head()

   sepal-length  sepal-width  petal-length  petal-width   Class
0           5.1          NaN           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

Memecah data

In [ ]:
irisdata_cleaned = irisdata.dropna()
X = irisdata_cleaned.drop('Class', axis=1)
Y = irisdata_cleaned['Class']

membagi data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20)

gunakan kernel polinomial

In [ ]:
SVMPoli = svm.SVC(kernel='poly', degree=8)
SVMPoli.fit(X_train, Y_train)

Y_pred = SVMPoli.predict(X_test)
Y_pred

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print('akurasi : ', accuracy_score(Y_test, Y_pred))

[[ 8  0  0]
 [ 0 14  0]
 [ 0  0  6]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       1.00      1.00      1.00        14
   Virginica       1.00      1.00      1.00         6

    accuracy                           1.00        28
   macro avg       1.00      1.00      1.00        28
weighted avg       1.00      1.00      1.00        28

akurasi :  1.0

Berikut untuk kernel gaussian

In [ ]:
SVMPoli = svm.SVC(kernel='rbf')
SVMPoli.fit(X_train, Y_train)

Y_pred = SVMPoli.predict(X_test)
Y_pred

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print('akurasi : ', accuracy_score(Y_test, Y_pred))

[[ 8  0  0]
 [ 0 13  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       1.00      0.93      0.96        14
   Virginica       0.86      1.00      0.92         6

    accuracy                           0.96        28
   macro avg       0.95      0.98      0.96        28
weighted avg       0.97      0.96      0.96        28

akurasi :  0.9642857142857143

Sedangkan untuk kernel sigmoid

In [ ]:
SVMPoli = svm.SVC(kernel='sigmoid')
SVMPoli.fit(X_train, Y_train)

Y_pred = SVMPoli.predict(X_test)
Y_pred

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print('akurasi : ', accuracy_score(Y_test, Y_pred))

[[ 0  0  8]
 [ 0  0 14]
 [ 0  0  6]]
              precision    recall  f1-score   support

      Setosa       0.00      0.00      0.00         8
  Versicolor       0.00      0.00      0.00        14
   Virginica       0.21      1.00      0.35         6

    accuracy                           0.21        28
   macro avg       0.07      0.33      0.12        28
weighted avg       0.05      0.21      0.08        28

akurasi :  0.21428571428571427

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

**POST TEST**

Panggil data yang telah diimport

In [ ]:
a = pd.read_excel('Date_Fruit_Datasets.xlsx')
a.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

pecah data menjadi data atribut dan data kelas

In [ ]:
X = a.drop('Class', axis=1)
Y = a['Class']

gunakan splitting untuk membagi data tersebut dalam data training dan data testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20)

Gunakan metode fit pada SVC untuk membentuk model SVM dari data training

In [ ]:
modelSVM = LinearSVC(dual=False, max_iter=10000)
modelSVM.fit(X_train, Y_train)

LinearSVC(dual=False, max_iter=10000)

gunakan model SVM dari hasill data training untuk membuat prediksi dari data

In [ ]:
Y_pred = modelSVM.predict(X_test)
Y_pred

array(['SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'DOKOL',
       'ROTANA', 'ROTANA', 'SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA',
       'ROTANA', 'SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA',
       'ROTANA', 'ROTANA', 'ROTANA', 'SOGAY', 'SAFAVI', 'ROTANA',
       'SAFAVI', 'SAFAVI', 'ROTANA', 'SAFAVI', 'SAFAVI', 'ROTANA',
       'SOGAY', 'ROTANA', 'SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA',
       'SAFAVI', 'SAFAVI', 'IRAQI', 'ROTANA', 'ROTANA', 'DOKOL', 'ROTANA',
       'ROTANA', 'ROTANA', 'DOKOL', 'SAFAVI', 'SAFAVI', 'SAFAVI',
       'ROTANA', 'DOKOL', 'SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA', 'SOGAY',
       'SAFAVI', 'DOKOL', 'SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA',
       'ROTANA', 'ROTANA', 'DOKOL', 'ROTANA', 'ROTANA', 'ROTANA',
       'ROTANA', 'ROTANA', 'SAFAVI', 'SAFAVI', 'DOKOL', 'ROTANA',
       'SAFAVI', 'DOKOL', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'DOKOL',
       'SAFAVI', 'SOGAY', 'SAFAVI', 'ROTANA', 'ROTANA', 'SAFAVI',
       'SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA',
       'SAFAVI', 'ROTANA', 'SAFAVI', 'SAFAVI', 'ROTANA', 'SAFAVI',
       'SAFAVI', 'SAFAVI', 'SAFAVI', 'SAFAVI', 'ROTANA', 'DOKOL',
       'SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA', 'SAFAVI', 'SAFAVI',
       'SAFAVI', 'ROTANA', 'ROTANA', 'ROTANA', 'DOKOL', 'SAFAVI',
       'ROTANA', 'SAFAVI', 'ROTANA', 'DOKOL', 'ROTANA', 'SOGAY', 'SOGAY',
       'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'SAFAVI',
       'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'SAFAVI', 'ROTANA',
       'SAFAVI', 'ROTANA', 'ROTANA', 'SAFAVI', 'ROTANA', 'ROTANA',
       'ROTANA', 'ROTANA', 'ROTANA', 'IRAQI', 'ROTANA', 'ROTANA',
       'ROTANA', 'ROTANA', 'ROTANA', 'DOKOL', 'ROTANA', 'ROTANA',
       'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA',
       'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA', 'ROTANA',
       'SAFAVI', 'DOKOL', 'ROTANA', 'ROTANA', 'ROTANA', 'DOKOL', 'ROTANA',
       'SAFAVI', 'SAFAVI', 'ROTANA', 'SAFAVI', 'ROTANA', 'SAFAVI',
       'DOKOL'], dtype=object)

Jalankan confusion matrix, precision, recall dan F1 untuk mengevaluasi hasil klasifikasi.

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print('akurasi : ', accuracy_score(Y_test, Y_pred))

[[ 0  0  0  0 10  0  0]
 [ 0  0  0  0 14  0  0]
 [ 0  0 14  0 28  2  0]
 [ 0  0  1  2  2  3  0]
 [ 0  0  1  0 36  0  0]
 [ 0  0  0  0  3 41  0]
 [ 0  0  0  0 16  1  6]]
              precision    recall  f1-score   support

       BERHI       0.00      0.00      0.00        10
      DEGLET       0.00      0.00      0.00        14
       DOKOL       0.88      0.32      0.47        44
       IRAQI       1.00      0.25      0.40         8
      ROTANA       0.33      0.97      0.49        37
      SAFAVI       0.87      0.93      0.90        44
       SOGAY       1.00      0.26      0.41        23

    accuracy                           0.55       180
   macro avg       0.58      0.39      0.38       180
weighted avg       0.67      0.55      0.51       180

akurasi :  0.55

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

gunakan kernel polinomial

In [ ]:
SVMPoli = svm.SVC(kernel='poly', degree=8)
SVMPoli.fit(X_train, Y_train)

Y_pred = SVMPoli.predict(X_test)
Y_pred

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print('akurasi : ', accuracy_score(Y_test, Y_pred))

[[ 0  1  1  0  4  3  1]
 [ 0  5  4  0  1  4  0]
 [ 0  1  8  0  0 35  0]
 [ 0  2  2  1  0  3  0]
 [ 0  6  0  0 29  0  2]
 [ 0  0  0  0  0 44  0]
 [ 0  3  5  0  0 11  4]]
              precision    recall  f1-score   support

       BERHI       0.00      0.00      0.00        10
      DEGLET       0.28      0.36      0.31        14
       DOKOL       0.40      0.18      0.25        44
       IRAQI       1.00      0.12      0.22         8
      ROTANA       0.85      0.78      0.82        37
      SAFAVI       0.44      1.00      0.61        44
       SOGAY       0.57      0.17      0.27        23

    accuracy                           0.51       180
   macro avg       0.51      0.37      0.35       180
weighted avg       0.52      0.51      0.45       180

akurasi :  0.5055555555555555

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Berikut untuk kernel gaussian

In [ ]:
SVMPoli = svm.SVC(kernel='rbf')
SVMPoli.fit(X_train, Y_train)

Y_pred = SVMPoli.predict(X_test)
Y_pred

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print('akurasi : ', accuracy_score(Y_test, Y_pred))

[[ 0  0  4  0  6  0  0]
 [ 0  6  7  0  1  0  0]
 [ 0  2 31  0  0 11  0]
 [ 0  0  4  3  1  0  0]
 [ 0  2  0  0 35  0  0]
 [ 0  0  0  0  0 44  0]
 [ 0  4 14  0  3  1  1]]
              precision    recall  f1-score   support

       BERHI       0.00      0.00      0.00        10
      DEGLET       0.43      0.43      0.43        14
       DOKOL       0.52      0.70      0.60        44
       IRAQI       1.00      0.38      0.55         8
      ROTANA       0.76      0.95      0.84        37
      SAFAVI       0.79      1.00      0.88        44
       SOGAY       1.00      0.04      0.08        23

    accuracy                           0.67       180
   macro avg       0.64      0.50      0.48       180
weighted avg       0.68      0.67      0.60       180

akurasi :  0.6666666666666666

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Sedangkan untuk kernel sigmoid

In [ ]:
SVMPoli = svm.SVC(kernel='sigmoid')
SVMPoli.fit(X_train, Y_train)

Y_pred = SVMPoli.predict(X_test)
Y_pred

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print('akurasi : ', accuracy_score(Y_test, Y_pred))

[[ 0  0  6  0  4  0  0]
 [ 0  0  7  0  7  0  0]
 [ 0  0 14  0 28  2  0]
 [ 0  0  1  0  7  0  0]
 [ 0  0 37  0  0  0  0]
 [ 0  0 15  0  6 23  0]
 [ 0  0  9  0 14  0  0]]
              precision    recall  f1-score   support

       BERHI       0.00      0.00      0.00        10
      DEGLET       0.00      0.00      0.00        14
       DOKOL       0.16      0.32      0.21        44
       IRAQI       0.00      0.00      0.00         8
      ROTANA       0.00      0.00      0.00        37
      SAFAVI       0.92      0.52      0.67        44
       SOGAY       0.00      0.00      0.00        23

    accuracy                           0.21       180
   macro avg       0.15      0.12      0.13       180
weighted avg       0.26      0.21      0.21       180

akurasi :  0.20555555555555555

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))